apiVersion: apps/v1
kind: Deployment
metadata:
  name: asap
  labels:
    app: asap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asap
  template:
    metadata:
      labels:
        app: asap
    spec:
      containers:
        - name: asap
          image: localhost:5000/asap:v1.0.5
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5226"
            - name: UDS_SOCKET_PATH
              value: "/var/run/dds-ambassador/grpc.sock"
          ports:
            - containerPort: 5226
              name: http
          volumeMounts:
            - name: uds-socket
              mountPath: /var/run/dds-ambassador
      volumes:
        - name: uds-socket
          persistentVolumeClaim:
            claimName: uds-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: asap
  labels:
    app: asap
spec:
  type: ClusterIP
  selector:
    app: asap
  ports:
    - name: http
      port: 5226
      targetPort: http
